# используем язык java. Travis CI также поддерживает другие языки
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту abrunan@yandex.ru если сборка упала
notifications:
  email:
    recipients:
      - abrunan@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="b5353c7f-df4e-4a92-ae6f-fe6f23acc473"